# Generated by Django 4.2.15 on 2024-08-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_location_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.location'),
        ),
    ]
