# Generated by Django 4.2.15 on 2024-08-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_inventoryitem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='part',
            field=models.CharField(default='NIMETUS', max_length=200),
            preserve_default=False,
        ),
    ]
